name: Nuget
on: [push, pull_request]

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install dotnet-format
      run: dotnet tool install -g dotnet-format

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Run dotnet format check
      run: dotnet format -wsa --check

  build:
    name: Build
    needs: check_format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ProjectName: [ BilibiliLiveRecordDownLoader.Shared, BilibiliLiveRecordDownLoader.BilibiliApi ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build
      shell: pwsh
      run: dotnet build -c Release ${{ matrix.ProjectName }}\${{ matrix.ProjectName }}.csproj

    - name: Push nuget packages
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      shell: pwsh
      run: |
        dotnet nuget push ${{ matrix.ProjectName }}\bin\Release\*.nupkg -s https://nuget.pkg.github.com/HMBSbige -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
        dotnet nuget push ${{ matrix.ProjectName }}\bin\Release\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NuGetAPIKey }} --skip-duplicate